### ISSUE TITLE
Fix  `coj_problems.go`

### ISSUE THREAD

**Issue by rendon** [algoristas/api#13]
I found out that this file does not compile, the `fmt` package is not being used and that's an error in Go, at least it does not compile in my machine, try `bin/deploy.sh`.

Also, when I fixed the problem in this file and saved the changes `gofmt` changed the indentation of the whole file, I don't want to do this because I will appear as the one who did the work when the only thing I did was changing the indentation.

Please, let's use `gofmt` to format our code, there's got to be a plugin for your favorite text editor.

**Comment by Gansito144** [comment]
I had the same issue trying to build Docker Image:
```
 ---> Running in 7995d8cfb268
# github.com/algoristas/api/problems
/go/src/github.com/algoristas/api/problems/coj_problems.go:4: imported and not used: "fmt"
```

**Comment by rendon** [comment]
Let's give @hopkins0 a chance to fix this.

**Comment by hopkins0** [comment]
Made the fix in [#14](https://github.com/algoristas/api/pull/14)

**Comment by Gansito144** [comment]
@hopkins0 Is this still an issue?

**Comment by rendon** [comment]
Ho, @hopkins0 fixed it.
