### ISSUE TITLE
Write code to determine if a user X has resolved problem Y in COJ

### ISSUE THREAD

**Issue by rendon** [algoristas/api#5]

**Comment by hopkins0** [comment]
Can I get it?

**Comment by hopkins0** [comment]
What else do we care to know?

We can recovery the languages in which the user X has solved the problem Y, among a couple of things more.

**Comment by Gansito144** [comment]
I think we need to focus only in the main question, since this functionality should be shared among others judges, maybe for other properties we need to check if is possible to get the same info over all platforms.

**Comment by rendon** [comment]
I would go with this one (from issue #3 ):
```
{
    "problem_id": 123,
    "owner_id": 456,
    "title": "Kefa and Park",
    "source": "http://codeforces.com/problemset/problem/580/C",
    "has_solved": "NO",
    "has_tried": "YES"
}
```

**Comment by hopkins0** [comment]
Issue approached in commit [3681e9a](https://github.com/algoristas/api/commit/3681e9abdbbef576daee76753be606063736ed7c)
