### ISSUE TITLE
Create Users controller

### ISSUE THREAD

**Issue by rendon** [algoristas/api#7]
This controller will handle all requests to the Users resource.

Users can be identified either by ID or user name. User names are unique for they do not fully identify a user, the ID does.

URI: `/users/{user_id|user_name}/...`

**Comment by Gansito144** [comment]
Will this user_id be the same across all different judges or how do you plan to handle that?

**Comment by rendon** [comment]
The user ID will be internal, the one we assign when they register in our platform. Each user will have alist of users names in other platforms, one for codeforces, one for COJ, etc.

**Comment by Gansito144** [comment]
Will this be the general profile for each user?

**Comment by rendon** [comment]
Yes, eventually, for now though it will return only basic info.

**Comment by rendon** [comment]
Fixed with https://github.com/algoristas/api/pull/9
